### ISSUE TITLE
Failure on R-devel on Windows

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/utf8#11]
https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/utf8-00check.html

Other platforms seem fine.

**Comment by patperry** [comment]
Thanks for reporting.

Any idea which commit in r-devel caused the test to fail?

Unfortunately I don't have the bandwidth to track this down. Since it's just some text-formatting C locale tests, I'm inclined to just skip the tests on Windows.

**Comment by krlmlr** [comment]
Sorry, no idea. I guess it's safe to wait a bit until CRAN contacts you, they might as well revert the change that caused this.

**Comment by warlicks** [comment]
Did the changes that @krlmlr made in #12 get submitted to CRAN? 
The checks are failing on Windows devel again. 
[https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/utf8-00check.html](https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/utf8-00check.html)

I'm happy to contribute to updating the tests here if that would be helpful.
