### ISSUE TITLE
Get R to keep UTF-8 Codepoint representation

### ISSUE THREAD

**Issue by lyons7** [krlmlr/utf8#2]
I have a weird problem in which I want emojis in a data set I'm working with to _stay_ in codepoint representation (i.e. as '\U0001f602'). I want to use the 'FindReplace' function from the [Data Combine package](https://cran.r-project.org/web/packages/DataCombine/DataCombine.pdf) to turn UTF-8 encodings into prose descriptions of emojis in a [dataset of YouTube comments](https://www.dropbox.com/s/3zwmn7vsvo9ihpv/sampletubedata.Rda?dl=0) (using a dictionary I made available [here](https://lyons7.github.io/portfolio/2017-10-04-emoji-dictionary/)). The only issue is that when I 'save' the output as an object in R the nice utf-8 encoding generated by `utf8_encode` for which I can use my dictionary, it disappears...

First I have to adjust the dictionary a bit:
`emojis$YouTube <- tolower(emojis$Codepoint)`
`emojis$YouTube <- gsub("u\\+","\\\\U000", emojis$YouTube)`

Convert to character so as to be able to use utf8_encode:
`emojimovie$test <- as.character(emojimovie$textOriginal)`

This works great, gives output of \U0001f595 (etc.) that can be matched with dictionary entries when it 'prints' in the console.
`utf8_encode(emojimovie$test)`

BUT, when I do this:
`emojimovie$text2 <- utf8_encode(emojimovie$test)`

and then:
`emoemo <- FindReplace(data = emojimovie, Var = "text2", replaceData = emojis, from = "YouTube", to = "Name", exact = TRUE)`

I get all NAs. When I look at the output in $text2 with `View` I don't see the \U0001f595, I see actual emojis. I think this is why the FindReplace function isn't working -- when it gets saved to an object it just gets represented as emojis again and the function can't find any matches. When I try `gsub("\U0001f602", "lolface", emojimovie$text2)`, however, I can actually match and replace things, but I don't want to do this for all ~2,000 or so emojis.... I've tried reading as much as I can about utf-8, but I can't understand why this is happening. Apologies if this is the wrong place to ask this question, but I'm stumped! :P

**Comment by patperry** [comment]
HI @lyons7 , I have some ideas about this, but can you post your question at stackoverflow.com instead? That way more people can see the question and the answer(s). Once you've done so, please post a link to the question here and close the issue.

**Comment by lyons7** [comment]
Sure! Question now available [here](https://stackoverflow.com/questions/47243155/get-r-to-keep-utf-8-codepoint-representation).
