### ISSUE TITLE
Compile error - uth8lite.h not found

### ISSUE THREAD

**Issue by fluteze** [krlmlr/utf8#6]
When I use devtools::install_github("patperry/r-utf8") I get the missing file error on a new (clean) install of R/Rtools/mingw64 etc.

I noticed the sub-project utf8lite has the file. Could you add some directions on how to include it via devtools::install_github?

OS Windows 10 / 64bit build 12699

**Comment by patperry** [comment]
This project uses a git submodule and unfortunately `devtools::install_git` no longer supports cloning with `git clone --recursive`. It is not currently possible to use `devtools` to install `utf8`.

I recommend following the instructions at https://github.com/patperry/r-utf8#development-version instead.
