### ISSUE TITLE
ranlib sometimes not available on Solaris?

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/utf8#7]
I'm having trouble checking *pillar* on Solaris with R-hub: *utf8* can't be installed because `ranlib` can't be found: https://builder.r-hub.io/status/pillar_1.2.2.9001.tar.gz-1ea56dcff8e44d29be07bbd460c0a7d2#L2037

The CRAN checks seem to work OK, though. I wonder if `ranlib` can be made optional so that the package can be installed on R-hub too, or perhaps substituted with `ar -s` (found in `man ranlib`).

```r
# install.packages("rhub")
rhub::check(platform = "solaris-x86-patched")
```

**Comment by patperry** [comment]
Maybe `ranlib` isn't necessary? At least according to https://stackoverflow.com/a/38244200/6233565 .

`jsonlite` skips the `ranlib` step: https://github.com/jeroen/jsonlite/blob/master/src/Makevars

**Comment by patperry** [comment]
Just submitted a new version to CRAN (1.1.4) that removes the call to `ranlib`. Tested on solaris with r-hub builder. This hopefully solves your issue.

**Comment by krlmlr** [comment]
Fantastic, thanks! Just checked *pillar* on R-hub successfully.

@gaborcsardi: FYI: The Solaris builders on R-hub don't seem to have `ranlib` available, but it seems this can be worked around.
